FROM ubuntu:focal

# set work directory
WORKDIR /usr/src/app



RUN apt-get update \
    && apt-get install software-properties-common -y \
    && apt-get install sudo -y 

RUN apt-get \
    install \ 
    git \
    python3 \
    python3-pip -y 

RUN apt-get \
    install \ 
    libmysqlclient-dev \
    python-dev -y 


# install dependencies
RUN pip install --upgrade pip 
COPY ./requirements.txt /usr/src/app
RUN pip install -r requirements.txt

# copy project
COPY . /usr/src/app

EXPOSE 8000

CMD ["python3", "manage.py", "runserver", "0.0.0.0:8000"]